name: CMake for Linux

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false
      
      matrix:
        include:
          - os: ubuntu-22.04
            arch: x86_64
          - os: ubuntu-22.04-arm
            arch: arm64

    steps:
    - uses: actions/checkout@v4

    - name: Add LLVM apt repository
      run: |
          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
          sudo add-apt-repository "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-20 main"
          sudo apt-get update

    - name: Install dependencies
      run: | 
        sudo apt-get install -y build-essential ninja-build cmake ccache llvm-20-dev clang-20 lld-20 llvm-20

    # build

    - name: Configure CMake
      working-directory: Babel
      run: |
        cmake -B build -G Ninja \
        -DCMAKE_BUILD_TYPE=Release \
        -DLLVM_DIR=/usr/lib/llvm-20/lib/cmake/llvm \
        -DCMAKE_EXE_LINKER_FLAGS="-static-libgcc -static-libstdc++"

    - name: Build
      working-directory: Babel
      run: cmake --build build --parallel 

    - name: Debug output
      run: |
        echo "=== Babel/build contents ==="
        find Babel/build -type f -name "babel-llvm"
        echo "=== Babel/staging contents ==="
        find Babel/staging -type f 2>/dev/null || echo "staging not found"

    - name: Install
      working-directory: Babel
      run: cmake --install build --prefix staging

    - name: Package compiler dependencies
      working-directory: Babel
      run: |
        CLANG_BIN=$(which clang-20)
        LLD_BIN=$(which ld.lld-20)
        
        mkdir -p staging/dependencies/lib staging/dependencies/lib/clang staging/dependencies/bin
        cp "$CLANG_BIN" staging/dependencies/bin/
        cp "$LLD_BIN" staging/dependencies/bin/ld.lld

        RESOURCE_DIR=$("$CLANG_BIN" --print-resource-dir)
        cp -r "$RESOURCE_DIR" staging/dependencies/lib/clang/20
        # Fetch LLVM license
        wget -q https://raw.githubusercontent.com/llvm/llvm-project/llvmorg-20.1.6/LICENSE.TXT \
        -O staging/dependencies/LLVM-LICENSE.TXT


    - name: Unpack linux sysroots
      working-directory: Babel/staging/dependencies/sysroots
      run: |
        for triple in x86_64-unknown-linux-gnu aarch64-unknown-linux-gnu x86_64-w64-windows-gnu; do
        mkdir -p "$triple"
        unzip -o "${triple}.zip" -d "$triple"
        rm "${triple}.zip"
        done

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: babel-linux-${{ matrix.arch }}
        path: Babel/staging
