# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake for Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
   build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache LLVM build
        id: cache-llvm
        uses: actions/cache/restore@v4
        with:
          path: C:/LLVM
          key: llvm-20.1.6-windows-x64-v1

      - name: Checkout LLVM
        if: steps.cache-llvm.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          repository: llvm/llvm-project
          ref: llvmorg-20.1.6
          path: llvm-project
          sparse-checkout: |
            llvm
            cmake

      - name: Build LLVM
        if: steps.cache-llvm.outputs.cache-hit != 'true'
        run: |
          cmake -S llvm-project/llvm -B llvm-build -G "Visual Studio 17 2022" `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_INSTALL_PREFIX="C:/LLVM" `
            -DLLVM_TARGETS_TO_BUILD="X86;AArch64" `
            -DLLVM_ENABLE_PROJECTS="" `
            -DLLVM_INCLUDE_TESTS=OFF `
            -DLLVM_INCLUDE_EXAMPLES=OFF `
            -DLLVM_INCLUDE_BENCHMARKS=OFF `
            -DLLVM_INCLUDE_DOCS=OFF
          cmake --build llvm-build --config Release --parallel
          cmake --install llvm-build --config Release


      - name: Save LLVM cache
        if: steps.cache-llvm.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: C:/LLVM
          key: llvm-20.1.6-windows-x64-v1

      - name: Configure CMake
        working-directory: Babel
        run: cmake -B build -G Ninja `
          -DCMAKE_BUILD_TYPE=Release `
          -DLLVM_DIR="C:/LLVM/lib/cmake/llvm"

      - name: Build
        working-directory: Babel
        run: cmake --build build --parallel


